"""team_and_player_fixes

Revision ID: 551f65b6602f
Revises: 6f72e9299911
Create Date: 2026-03-09 22:05:44.344109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '551f65b6602f'
down_revision: Union[str, Sequence[str], None] = '6f72e9299911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players') as batch_op:
        batch_op.create_unique_constraint('uq_players_ciId', ['ciId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players') as batch_op:
        batch_op.drop_constraint('uq_players_ciId', type_='unique')
    # ### end Alembic commands ###
